### ISSUE TITLE
Sets <<Cubes>>

### ISSUE THREAD

**Issue by ldwoolley** [snakify/content#19]
I can't seem to pass the <<Cubes>> test.  The output looks identical to the test, but says that it doesn't pass.  Here is the code:
```python
acount, bcount = [int(i) for i in input().split(' ')]
aset, bset, cset = set(), set(), set()
for a in range(acount):
    aset.add(int(input()))
for b in range(bcount):
    bset.add(int(input()))
print(len(aset & bset))
for c in aset & bset:
    print(c)
print(len(aset - bset))
for a in aset - bset:
    print(a)
print(len(bset - aset))
for b in bset - aset:
    print(b)    
```
Heres the produced output, that looks just like the test case:
```python
2
0
1
2
9
10
1
3

```
Did I miss something in the test?  All but the first one pass.

**Comment by vpavlenko** [comment]
I'm sorry, but you're hitting the difference between the visualizer (i.e. what do you see when clicking Run) and the grader (i.e. what do you see when you submit solution). We plan to fix it in a month, but before that visualizer and grader are using two different Python implementations. And in the latter implementation your program outputs the data without sorting, like this:

```
2
0
1
2
10
9
1
3
```

While we're going to fix this difference, could you please fix your solution so that it sorts the sets on printing, as requested in the problem statement?

Sorry for inconvenience.

**Comment by ldwoolley** [comment]
That makes sense.  I usually work against the test results, and since I can only see, the visualizer, I figured I had met the requirements without the extra step.  I am still impressed with web visualizers, so no harm done.
